database: hsqldb

spring:
  datasource:
    schema: classpath*:/${database}/schema.sql
    data: classpath*:/${database}/data.sql
    url: jdbc:h2:mem:testdb;MODE=mysql;
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: debug
    org:
      hibernate:
        SQL: debug
        type: trace